### ISSUE TITLE
We should not prompt for a chain if we pass a devet setting

### ISSUE THREAD

**Issue by remyroy** [eth-educators/ethstaker-deposit-cli#46]
For instance, if I pass a `--devnet_chain_setting` to the `generate-bls-to-execution-change`, without passing a `--chain`, I will be prompted for a chain. I should not be since I am already passing a chain setting. This should be generalize to all commands that accept a devnet chain setting.

**Comment by yorickdowne** [comment]
Once #115 has been discussed and is in, I can re-use that code for this, and make it a bit more generic. I am thinking a callback that can disable the prompt of a list of options, passed into the callback. Right now it disables all; this would disable some.

The code to re-enable specific things because of bleed-through on `CLIRunner()` will need to remain alas, unless we find another way.
