### ISSUE TITLE
Test and warn for short or weak passwords [TOB-EF-DEP-003]

### ISSUE THREAD

**Issue by remyroy** [eth-educators/ethstaker-deposit-cli#71]
TOB-EF-DEP-003 in [the original security assessment](https://github.com/trailofbits/publications/blob/master/reviews/ETH2DepositCLI.pdf) recommends to test and check for short or weak passwords.

We should probably warn or prevent using short or weak passwords, especially for the keystore password.

**Comment by valefar-on-discord** [comment]
Can use this library: https://github.com/dropbox/zxcvbn

**Comment by valefar-on-discord** [comment]
Turns out zxcvbn is pretty much dead and the [python version](https://github.com/dwolfhub/zxcvbn-python) also looks to have been [abandoned](https://github.com/dwolfhub/zxcvbn-python/issues/73)

I don't think we should use this library and find an alternative or determine an implementation strategy.

**Comment by yorickdowne** [comment]
I believe our best bet is to just check for length, and change it from the current 8 to minimum 12.

"As recently as 2020, NIST revised their password guidelines to emphasize password length over complexity requirements" 

Length beats complexity every time. A long passphrase "correct horse battery staple" is far harder to crack than 8 random characters with special.

We are already checking for a length of 8, which is the minimum length NIST recommends.
